### PR TITLE
Added joystickTutorial.py

### PR DESCRIPTION
**Pull request by johnbatty**

### CODE REVIEW

**Comment by johnbatty** [comment]
I renamed the example as you suggested.

I did originally write the example using joystick events, but found that the events are generated much faster than the display can update, so you get a backlog (which seem to be queued up somewhere).  You therefore end up getting a delay in the position displayed - and it keeps on moving after you stop moving the joystick.  So there's definitely some buffering going on somewhere.  I've added an example using events so you can compare the two.  I think that this demonstrates that for the joystick you are probably better off polling to make feedback as tight as possible.  See what you think.  Perhaps I could add comments to explain this (if you agree), and you could add both examples (as the other module examples have event and polling examples).  Or if you want I could write new sections for the docs if you wanted to include the examples in there with the other Python examples.

**Comment by pixelpixi** [comment]
Oh I see. Hmm, yeah the events are probably getting buffered in the usb-serial buffers.

Another way to do it might be to handle the event, store the new position in a variable, and set a "needs update" flag. Then in the main loop, redraw the display if the flag is set. I think that would keep the events from getting backed up. It's probably a better software engineering practice than what I originally suggested anyway since it provides some model/view separation.

Would you be up for posting this as a project on hackster.io? I think that would be perfect, and you'd also be able to easily edit it without having to wait on me to upload it to the docs site. If you don't want to do that, I'm still happy to include it in this repo though.

**Comment by johnbatty** [comment]
I'll try updating it as you suggest - that seems like a nice idea.

I'm up for posting something on hackster.io, but might do something a little more advanced.  Perhaps a little game using joystick and display (and possibly knob)...  I only got my Modulo on Friday, so I'm still playing - and just thought you might want a Python joystick example as there isn't one in the current set.

**Comment by pixelpixi** [comment]
There is one joystick python example ( http://docs.modulo.co/example-joystick-motor-python.html ) but it uses the joystick and motor driver, not the joystick and display like yours. Glad you're getting started so quickly after getting it and thanks for contributing!

**Comment by johnbatty** [comment]
I only have the Tea-Time set of modules, so no motor :-(

I've updated the example with events again along the lines you suggested.  Although rather than querying the state within the callback (which would require multiple global variables), I just set a flag, and then just test that flag within the main loop.

No problem if you don't want to take this into the main repro.  Just wanted to make it available!

**Comment by pixelpixi** [comment]
Oh makes sense with tea-time. Yeah, it's probably good to have more tutorials in case people don't have the exact modulos that they existing tutorials were built for. Thanks a lot for writing this and submitting the pull request!

**Pull request merged**
